"""The knowledge base — Trace's second brain as a plain markdown vault (kb/).

Two one-way flows, never both for the same file (the single rule that keeps
one source of truth):

  kb/<project>/inbox/      SOURCES — drop a meeting note here; the vault
                           watcher ingests it as an immutable, audit-chained
                           EPISODE and runs the full pipeline on it
                           (capture -> invalidation -> court).
  kb/<project>/decisions/  PROJECTIONS — every decision rendered as a markdown
  kb/<project>/court/      note with YAML frontmatter and wikilinks,
  kb/<project>/episodes/   regenerated from the store after every write and
                           never read back.

The store (SQLite + the SHA-256 audit chain) remains the only record. Each
generated note carries a `record_sha256` of the underlying row, so an edited
projection is detectable (`verify_vault`) — the vault-level analogue of
`verify_audit_chain`.

The vault is Obsidian-compatible by construction — filenames equal decision
ids, so `[[408213-D-001]]` resolves and the graph view IS the decision graph
(supersession chains, court verdicts, evidence links) — but nothing here
depends on Obsidian: it is a folder of markdown, readable in any editor.
Frontmatter follows the MADR (ADR) convention: a `status` lifecycle field
(valid / proposed / rejected / superseded) plus explicit `superseded_by` /
`supersedes` links. This module is keyless and deterministic — no LLM, no
network; ingestion (which needs Qwen) lives in vault_watcher.py.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Optional

from court import get_court_records
from store import (
    Decision, get_all_decisions, get_episodes, get_project_code,
)

KB_ROOT = Path(__file__).resolve().parent.parent / "kb"

BANNER = ("> [!warning] Generated by Trace — do not edit.\n"
          "> This note is a PROJECTION of the tamper-evident decision store; "
          "the store is the record. Edits here change nothing real and will be "
          "overwritten on the next export. Commentary belongs in your own notes "
          "— link this one instead.")


def _row_sha(d: Decision) -> str:
    canonical = json.dumps({
        "id": d.id, "statement": d.statement, "status": d.status,
        "rationale": d.rationale, "assumptions": d.assumptions,
        "valid_from": d.valid_from, "valid_to": d.valid_to,
        "superseded_by": d.superseded_by,
    }, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _fm(lines: list[tuple[str, object]]) -> str:
    """Deterministic YAML frontmatter (hand-rendered: stable key order, no
    dependency on dumper quirks)."""
    out = ["---"]
    for key, val in lines:
        if val is None or val == "" or val == []:
            continue
        if isinstance(val, list):
            out.append(f"{key}:")
            out.extend(f'  - "{v}"' for v in val)
        else:
            out.append(f'{key}: "{val}"')
    out.append("---")
    return "\n".join(out)


def _decision_note(d: Decision, project: str, supersedes: Optional[str]) -> str:
    fm = _fm([
        ("id", d.id),
        ("project", project),
        ("type", "decision"),
        ("status", d.status),                      # MADR-style lifecycle field
        ("discipline", d.discipline),
        ("importance", d.importance),
        ("valid_from", d.valid_from),
        ("valid_to", d.valid_to),
        ("superseded_by", f"[[{d.superseded_by}]]" if d.superseded_by else None),
        ("supersedes", f"[[{supersedes}]]" if supersedes else None),
        ("source_episode", f"[[{d.source_episode}]]" if d.source_episode else None),
        ("authors", d.author),
        ("generated-by", "trace"),
        ("record_sha256", _row_sha(d)),
    ])
    body = [fm, "", BANNER, "", f"# {d.id} — {d.statement}", "",
            f"**Status:** {d.status.upper()}"]
    if d.rationale:
        body += ["", "## Why", "", d.rationale]
    if d.assumptions:
        body += ["", "## Assumptions (the premises this decision rests on)", ""]
        body += [f"- {a}" for a in d.assumptions]
    links = []
    if d.superseded_by:
        links.append(f"- Superseded by [[{d.superseded_by}]]")
    if supersedes:
        links.append(f"- Supersedes [[{supersedes}]]")
    if d.source_episode:
        links.append(f"- Source episode: [[{d.source_episode}]]")
    if links:
        body += ["", "## Trail", ""] + links
    return "\n".join(body) + "\n"


def _court_note(r: dict, project: str) -> str:
    name = f"COURT-{r['proposal_id']}"
    fm = _fm([
        ("id", name),
        ("project", project),
        ("type", "court-verdict"),
        ("verdict", r["verdict"]),
        ("proposal", f"[[{r['proposal_id']}]]" if r["proposal_id"] else None),
        ("breaks", f"[[{r['breaks_id']}]]" if r["breaks_id"] else None),
        ("citation", r["citation"]),
        ("created_at", r["created_at"]),
        ("generated-by", "trace"),
    ])
    body = [fm, "", BANNER, "",
            f"# Decision court — {r['verdict']}: [[{r['proposal_id']}]]", ""]
    if r["breaks_id"]:
        body.append(f"**Breaks:** [[{r['breaks_id']}]] · {r['citation']}")
    body += ["", "## For (Proposer)", "", r["for_argument"] or "—",
             "", "## Against (Guardian)", "", r["against_argument"] or "—",
             "", "## Judge's rationale", "", r["rationale"] or "—"]
    return "\n".join(body) + "\n"


def _episode_note(e, project: str) -> str:
    fm = _fm([
        ("id", e.id),
        ("project", project),
        ("type", "episode"),
        ("source_path", e.path),
        ("sha256", e.sha256),
        ("ingested_at", e.ingested_at),
        ("generated-by", "trace"),
    ])
    return "\n".join([fm, "", "> [!note] Immutable source episode — ingested verbatim, "
                      "on the audit chain.", "", e.body]) + "\n"


def _index_note(conn, project: str, title: str) -> str:
    fm = _fm([("project", project), ("type", "index"), ("generated-by", "trace")])
    rows = ["| id | status | decision |", "|---|---|---|"]
    for d in get_all_decisions(conn):
        rows.append(f"| [[{d.id}]] | {d.status} | {d.statement[:80]} |")
    return "\n".join([fm, "", f"# {title} — decision record", "", BANNER, ""] + rows) + "\n"


def export_vault(conn, project: str, root: Optional[Path] = None, title: str = "") -> list[Path]:
    """Render the whole store into kb/<project>/ — deterministic, keyless.
    Returns the list of files written. Existing projection files are replaced
    (they are projections; the store is the record); inbox/ is never touched."""
    root = Path(root) if root else KB_ROOT
    base = root / project
    written: list[Path] = []
    (base / "inbox").mkdir(parents=True, exist_ok=True)  # the drop zone exists by default

    decisions = get_all_decisions(conn)
    supersedes = {d.superseded_by: d.id for d in decisions if d.superseded_by}

    ddir = base / "decisions"
    ddir.mkdir(parents=True, exist_ok=True)
    for old in ddir.glob("*.md"):
        old.unlink()
    for d in decisions:
        p = ddir / f"{d.id}.md"
        p.write_text(_decision_note(d, project, supersedes.get(d.id)), encoding="utf-8")
        written.append(p)

    cdir = base / "court"
    cdir.mkdir(parents=True, exist_ok=True)
    for old in cdir.glob("*.md"):
        old.unlink()
    for r in get_court_records(conn):
        p = cdir / f"COURT-{r['proposal_id']}.md"
        p.write_text(_court_note(r, project), encoding="utf-8")
        written.append(p)

    edir = base / "episodes"
    edir.mkdir(parents=True, exist_ok=True)
    for old in edir.glob("*.md"):
        old.unlink()
    for e in get_episodes(conn):
        p = edir / f"{e.id}.md"
        p.write_text(_episode_note(e, project), encoding="utf-8")
        written.append(p)

    idx = base / "_index.md"
    idx.write_text(_index_note(conn, project, title or project), encoding="utf-8")
    written.append(idx)
    return written


def verify_vault(conn, project: str, root: Optional[Path] = None) -> list[str]:
    """The vault-level analogue of verify_audit_chain: compare each decision
    note's stored record_sha256 against the live store row. Returns the ids
    whose projection diverges (edited, stale, or missing) — empty means the
    vault faithfully mirrors the record."""
    root = Path(root) if root else KB_ROOT
    ddir = root / project / "decisions"
    bad: list[str] = []
    for d in get_all_decisions(conn):
        p = ddir / f"{d.id}.md"
        if not p.is_file():
            bad.append(d.id)
            continue
        text = p.read_text(encoding="utf-8")
        want = f'record_sha256: "{_row_sha(d)}"'
        if want not in text:
            bad.append(d.id)
    return bad


if __name__ == "__main__":
    # Regenerate the committed demo vault for every project: keyless, offline.
    from scenarios import PROJECTS, build_store
    for key, meta in PROJECTS.items():
        conn = build_store(key)
        files = export_vault(conn, key, title=meta["title"])
        code = get_project_code(conn)
        print(f"{key} [{code}]: {len(files)} notes -> {KB_ROOT / key}")
