"""The knowledge base: kb.py (projection — keyless, deterministic) and
vault_watcher.py (ingestion — the full pipeline on a dropped note). The single
invariant under test: inbox notes are SOURCES, generated notes are PROJECTIONS,
never both — the store stays the only record."""
import json
from types import SimpleNamespace

from kb import export_vault, verify_vault
from scenarios import PROJECTS, build_store
from store import (
    Decision, add_decision, connect, get_all_decisions, get_decision, init_db,
    verify_audit_chain,
)
from vault_watcher import ingest_note, parse_frontmatter, watch


# ── projection ───────────────────────────────────────────────────────────────

def test_export_writes_a_note_per_decision_with_frontmatter(tmp_path):
    conn = build_store("tanglin-rise")
    files = export_vault(conn, "tanglin-rise", tmp_path)
    ddir = tmp_path / "tanglin-rise" / "decisions"
    note = (ddir / "408213-D-001.md").read_text(encoding="utf-8")
    assert 'status: "valid"' in note
    assert 'generated-by: "trace"' in note
    assert "Generated by Trace — do not edit" in note
    rejected = (ddir / "408213-D-002.md").read_text(encoding="utf-8")
    assert 'status: "rejected"' in rejected
    assert len([f for f in files if f.parent == ddir]) == len(get_all_decisions(conn))


def test_export_renders_the_decision_graph_as_wikilinks(tmp_path):
    conn = build_store("tanglin-rise")
    export_vault(conn, "tanglin-rise", tmp_path)
    base = tmp_path / "tanglin-rise"
    old = (base / "decisions" / "408213-D-004.md").read_text(encoding="utf-8")
    new = (base / "decisions" / "408213-D-006.md").read_text(encoding="utf-8")
    assert "[[408213-D-006]]" in old            # superseded_by edge
    assert "[[408213-D-004]]" in new            # reverse supersedes edge
    court = (base / "court" / "COURT-408213-D-002.md").read_text(encoding="utf-8")
    assert "[[408213-D-002]]" in court and "[[408213-D-001]]" in court
    assert 'verdict: "REJECT"' in court


def test_export_writes_an_index_and_inbox_exists(tmp_path):
    conn = build_store("pearl-vista")
    export_vault(conn, "pearl-vista", tmp_path, title=PROJECTS["pearl-vista"]["title"])
    idx = (tmp_path / "pearl-vista" / "_index.md").read_text(encoding="utf-8")
    assert "[[629481-D-001]]" in idx and "rejected" in idx
    assert (tmp_path / "pearl-vista" / "inbox").is_dir()   # the drop zone


def test_export_is_deterministic_and_regenerates(tmp_path):
    conn = build_store("kranji-hub")
    export_vault(conn, "kranji-hub", tmp_path)
    p = tmp_path / "kranji-hub" / "decisions" / "517294-D-001.md"
    first = p.read_text(encoding="utf-8")
    p.write_text(first + "\nhuman edit\n", encoding="utf-8")  # someone edits a projection
    export_vault(conn, "kranji-hub", tmp_path)                # regeneration overwrites
    assert p.read_text(encoding="utf-8") == first


def test_verify_vault_detects_an_edited_projection(tmp_path):
    conn = build_store("kranji-hub")
    export_vault(conn, "kranji-hub", tmp_path)
    assert verify_vault(conn, "kranji-hub", tmp_path) == []
    p = tmp_path / "kranji-hub" / "decisions" / "517294-D-001.md"
    p.write_text(p.read_text(encoding="utf-8").replace(
        'record_sha256: "', 'record_sha256: "0000'), encoding="utf-8")
    assert verify_vault(conn, "kranji-hub", tmp_path) == ["517294-D-001"]


# ── ingestion ────────────────────────────────────────────────────────────────

def _tool_call(args: dict):
    return SimpleNamespace(function=SimpleNamespace(arguments=json.dumps(args)))


def _capture_client(decisions: list[dict], extra_texts: list[str] = ()):
    """First call returns record_decision tool-calls; later calls return the
    queued plain texts (premise check / court roles)."""
    queue = list(extra_texts)
    calls = {"n": 0}

    def create(**kw):
        calls["n"] += 1
        if calls["n"] == 1:
            msg = SimpleNamespace(content="", tool_calls=[_tool_call(a) for a in decisions])
        else:
            msg = SimpleNamespace(content=queue.pop(0), tool_calls=None)
        return SimpleNamespace(choices=[SimpleNamespace(message=msg)])
    return SimpleNamespace(chat=SimpleNamespace(completions=SimpleNamespace(create=create)))


NOTE = """---
project: demo
date: 2026-02-01
---
## Site meeting
We will fix the north facade render this quarter.
"""


def _fresh():
    conn = connect(":memory:")
    init_db(conn)
    return conn


def test_ingest_stores_episode_and_decision_with_provenance():
    conn = _fresh()
    client = _capture_client([{"statement": "Repair the north facade render",
                               "discipline": "facade", "rationale": "spalling found",
                               "assumptions": ["scope per survey"], "author": ["H. Nair"]}])
    out = ingest_note(conn, NOTE, path="inbox/meeting.md", client=client)
    assert out["episode"] == "E-001" and out["duplicate"] is False
    d = get_decision(conn, out["captured"][0]["id"])
    assert d.source_episode == "E-001"              # provenance is a real reference
    assert d.valid_from == "2026-02-01T00:00:00Z"   # the note's date, not ingest time
    assert d.status == "valid"
    assert verify_audit_chain(conn)[0] is True      # ingest + add, all on the chain


def test_ingest_routes_conflicts_through_the_court():
    conn = _fresh()
    add_decision(conn, Decision(statement="Facade = non-combustible rainscreen",
                                discipline="facade", recorded_at="2026-01-01T00:00Z"))
    client = _capture_client(
        [{"statement": "Swap facade to PE-core ACP", "discipline": "facade",
          "rationale": "cost", "assumptions": [], "author": ["contractor"],
          "cladding_combustible": True}],
        extra_texts=["proposer prose", "guardian prose", "judge prose"])
    out = ingest_note(conn, NOTE, client=client,
                      context={"building": {"height_m": 95, "boundary_distance_m": 7.5}})
    assert out["alerts"] and out["verdicts"]
    proposal = get_decision(conn, out["captured"][0]["id"])
    assert proposal.status == "rejected"            # the court's fate on the row


def test_ingest_never_eats_trace_projections():
    conn = _fresh()
    projection = '---\ngenerated-by: "trace"\nid: "D-001"\n---\n# D-001 — x\n'
    assert ingest_note(conn, projection, client=None) is None
    assert conn.execute("SELECT COUNT(*) AS n FROM episodes").fetchone()["n"] == 0


def test_ingest_dedupes_identical_content():
    conn = _fresh()
    client = _capture_client([{"statement": "s", "discipline": "mep",
                               "rationale": "r", "assumptions": [], "author": []}])
    first = ingest_note(conn, NOTE, path="inbox/a.md", client=client)
    again = ingest_note(conn, NOTE, path="inbox/renamed.md", client=None)  # no LLM call
    assert first["duplicate"] is False and again["duplicate"] is True
    assert again["episode"] == first["episode"]
    assert len(get_all_decisions(conn)) == 1        # captured once, not twice


def test_parse_frontmatter_is_tolerant():
    assert parse_frontmatter("no frontmatter") == ({}, "no frontmatter")
    fm, body = parse_frontmatter("---\nproject: x\n---\nbody")
    assert fm == {"project": "x"} and body == "body"
    fm, _ = parse_frontmatter("---\n:bad yaml [\n---\nbody")
    assert fm == {}


# ── the loop, end to end (bounded polls, fake client, offline) ───────────────

def test_watch_ingests_a_dropped_note_and_reexports(tmp_path):
    conn = build_store("tanglin-rise")
    inbox = tmp_path / "tanglin-rise" / "inbox"
    inbox.mkdir(parents=True)
    (inbox / "meeting.md").write_text(
        "---\nproject: tanglin-rise\ndate: 2026-02-01\n---\n## Site meeting\n"
        "We will repair the lobby soffit.\n", encoding="utf-8")
    client = _capture_client([{"statement": "Repair the lobby soffit",
                               "discipline": "architecture", "rationale": "leak",
                               "assumptions": ["scope agreed"], "author": ["K. Lim"]}])
    watch("tanglin-rise", conn=conn, root=tmp_path, client=client, max_polls=1)
    new = [d for d in get_all_decisions(conn) if d.statement == "Repair the lobby soffit"]
    assert len(new) == 1 and new[0].id == "408213-D-007"
    note = (tmp_path / "tanglin-rise" / "decisions" / "408213-D-007.md").read_text(encoding="utf-8")
    assert 'status: "valid"' in note                # the vault reflects the ingest
    episode = (tmp_path / "tanglin-rise" / "episodes" / "408213-E-001.md").read_text(encoding="utf-8")
    assert "Site meeting" in episode                # the source is readable provenance


def test_export_never_deletes_a_user_authored_file(tmp_path):
    conn = build_store("kranji-hub")
    export_vault(conn, "kranji-hub", tmp_path)
    mine = tmp_path / "kranji-hub" / "decisions" / "my-own-commentary.md"
    mine.write_text("# my note\nlinks [[517294-D-001]]\n", encoding="utf-8")
    export_vault(conn, "kranji-hub", tmp_path)          # regeneration
    assert mine.is_file()                                # user file untouched


def test_verify_vault_detects_a_body_edit_even_with_intact_sha_line(tmp_path):
    conn = build_store("kranji-hub")
    export_vault(conn, "kranji-hub", tmp_path)
    p = tmp_path / "kranji-hub" / "decisions" / "517294-D-001.md"
    p.write_text(p.read_text(encoding="utf-8").replace(
        "## Why", "## Why (doctored)"), encoding="utf-8")  # sha line left intact
    assert verify_vault(conn, "kranji-hub", tmp_path) == ["517294-D-001"]


def test_frontmatter_escapes_quotes_in_statements(tmp_path):
    conn = _fresh()
    add_decision(conn, Decision(statement='Facade spec per "or equivalent" clause \\ rev B'))
    export_vault(conn, "demo", tmp_path)
    import yaml as _yaml
    text = (tmp_path / "demo" / "decisions" / "D-001.md").read_text(encoding="utf-8")
    fm = _yaml.safe_load(text.split("---")[1])
    assert fm["id"] == "D-001"                           # frontmatter still parses


def test_ingest_skips_a_note_addressed_to_another_project():
    conn = _fresh()
    misdropped = "---\nproject: tanglin-rise\n---\nMeeting note."
    assert ingest_note(conn, misdropped, project="pearl-vista", client=None) is None
    assert conn.execute("SELECT COUNT(*) AS n FROM episodes").fetchone()["n"] == 0


def test_pearl_vista_ingest_is_gated_by_the_bca_pack():
    # The claim on the tin: pearl-vista's invalidation is gated by the SECOND
    # Singapore authority's pack. A note proposing to skip the Competent Person
    # must trip BCA-PFI-competent-person and reach the court.
    from scenarios import PROJECTS, project_rules
    conn = build_store("pearl-vista")
    client = _capture_client(
        [{"statement": "Skip the Competent Person this cycle; use contractor drone footage",
          "discipline": "facade", "rationale": "cost", "assumptions": [],
          "author": ["managing agent"], "inspection_competent_person": False}],
        extra_texts=["proposer prose", "guardian prose", "judge prose"])
    out = ingest_note(conn, "## MCST meeting\nSkip the CP appointment.",
                      project="pearl-vista", context=PROJECTS["pearl-vista"]["context"],
                      client=client, rules=project_rules("pearl-vista"))
    assert out["alerts"] and "BCA" in out["alerts"][0] or "Competent Person" in out["alerts"][0]
    assert out["verdicts"]                               # the court convened
    from store import get_decision as _get
    assert _get(conn, out["captured"][0]["id"]).status == "rejected"
